Add buttons for 1D, 1W, and 1M price charts
SetProtocol/index-ui pull request #98
Opened 2020-12-03 22:46 UTC by ncitron

## Changes
- Price charts have buttons for different timeframes
- On the 1D timeframe, dates are replaced with time using the `hh:mm` format

2020-12-05 00:30 UTC, controtie requested changes
Really good stuff! A couple notes:
1. Rebase off master. It looks like you're duplicating some commits on your card work from earlier which has been merged. Lmk if you need help with that
2. Take a look at the price charts on http://localhost:3000/dpi or http://localhost:3000/index
There's some expensive calculations in how you're handling price calculation which noticeably slows down the price chart component.

I've added some notes on places where you can look for speed improvements. But if you can fix the lagging price calculations in a different way thats fine.

Beyond that, looks pretty slick! 🦉

2020-12-05 00:30 UTC, controtie commented on src/components/SimplePriceChart/SimplePriceChart.tsx
> +  }
Maybe look into optimizing the above section? Could try memoizing `{ x: localeDateString }`

2020-12-05 00:30 UTC, controtie commented on src/components/SimplePriceChart/SimplePriceChart.tsx
> +  const [price, setPrice] = useState(data)
rename to something more descriptive like priceData

2020-12-05 00:30 UTC, controtie commented on src/components/SimplePriceChart/SimplePriceChart.tsx
> +  );
this radial gradient doesn't seem to be showing up very clearly? unless I'm missing something...
If not maybe remove?

2020-12-05 00:30 UTC, controtie commented on src/views/DPI/components/MarketData.tsx
> +      }
Also may look into optimizing the above calculation with memos

2020-12-05 00:30 UTC, controtie commented on src/views/DPI/components/MarketData.tsx
> +      }
Ditto the above

2020-12-05 02:44 UTC, ncitron commented
So I've done a bit of investigating on the lag issues for the charts. It appears to me that regardless of whether you run the current master or my PR, the graph appears to be laggy. This makes sense since both the current version and my version make repeated calls to `priceData.toDateString()`, which is what you proposed I optimize. This lag goes away however when you create an optimized production build using `yarn run build` and `serve -s build` to run it. This is why the version running in prod looks smooth. I am still happy to attempt to memoize it, but as far as I can tell this will cause no performance gains compared to the current version (as the current version does not memoize it). Let me know how you want me to proceed, and I'll push the other changes.

2020-12-05 03:12 UTC, controtie commented
Alright, I'll do a test deploy and get back to you

2020-12-06 04:23 UTC, controtie commented
Deploy looks good 👍

2020-12-06 04:23 UTC, controtie approved these changes

2020-12-06 04:23 UTC, merged